<?xml version='1.0' encoding='UTF-8'?>
<testsuites name="results">
  <testsuite name="all" package="all" tests="0">
    <property name="random_seed" value="1568843778" />
    <testcase classname="test_adder" name="adder_basic2_test" ratio_time="0.03346363789021309" sim_time_ns="0.000401" time="0.011983156204223633" />
    <testcase classname="test_adder" name="adder_basic_test" ratio_time="0.03969123077286136" sim_time_ns="0.000401" time="0.010102987289428711" />
    <testcase classname="test_adder" name="adder_random_test" ratio_time="0.03653717776377815" sim_time_ns="0.0004009999999999999" time="0.010975122451782227">
      <failure message="Test failed with random_seed=1568843778" stderr="" stdout="'Randomised test failed with: 4 + 2 = 6'" />
    </testcase>
  </testsuite>
</testsuites>
